all:
		g++ -std=c++11 tipos.cpp -o exe
		./exe Clientes50.csv 50
		./exe Clientes100.csv 100
		./exe Clientes200.csv 200
		./exe Clientes300.csv 300
		./exe Clientes400.csv 400
		./exe Clientes500.csv 500
		./exe Clientes600.csv 600
		./exe Clientes700.csv 700
		./exe Clientes800.csv 800
		./exe Clientes900.csv 900
		./exe Clientes1000.csv 1000

