all:
		g++ -std=c++11 PLRP_GAMA/PLRP_gama3.cpp -o exe
		./exe Entradas/Clientes50.csv Entradas/Depositos30.csv Salidas/Ruta_50_30.txt
		./exe Entradas/Clientes100.csv Entradas/Depositos30.csv Salidas/Ruta_100_30.txt
		./exe Entradas/Clientes200.csv Entradas/Depositos50.csv Salidas/Ruta_200_50.txt
		./exe Entradas/Clientes300.csv Entradas/Depositos50.csv Salidas/Ruta_300_50.txt
		./exe Entradas/Clientes400.csv Entradas/Depositos70.csv Salidas/Ruta_400_70.txt
		./exe Entradas/Clientes500.csv Entradas/Depositos70.csv Salidas/Ruta_500_70.txt
		./exe Entradas/Clientes600.csv Entradas/Depositos100.csv Salidas/Ruta_600_100.txt
		./exe Entradas/Clientes700.csv Entradas/Depositos100.csv Salidas/Ruta_700_100.txt
		./exe Entradas/Clientes800.csv Entradas/Depositos200.csv Salidas/Ruta_800_200.txt
		./exe Entradas/Clientes900.csv Entradas/Depositos200.csv Salidas/Ruta_900_200.txt
		./exe Entradas/Clientes1000.csv Entradas/Depositos200.csv Salidas/Ruta_1000_200.txt
