all:		
		g++ -std=c++11 CSV_Maker.cpp -o csv_make
		./csv_make 50 Clientes/clientes50.csv
		./csv_make 100 Clientes/clientes100.csv
		./csv_make 200 Clientes/clientes200.csv
		./csv_make 300 Clientes/clientes300.csv
		./csv_make 400 Clientes/clientes400.csv
		./csv_make 500 Clientes/clientes500.csv
		./csv_make 1000 Clientes/clientes1000.csv
